### PR TITLE
fix #332

### LINKED ISSUE #332: window.jasmine is not defined until runTests()
Jasmine's interface is being added to `global` inside `runTests()` ([see here](https://github.com/xolvio/meteor-jasmine/blob/master/src/client/runTests.js#L10))

```javascript
console.log(window.jasmine); // undefined

describe('this weekend', function() {
  console.log(window.jasmine); // defined

  it('should be amazing', function() {
    expect(weekend).toBe(amazing);
  });
});
```

Let's say someone is using `angular-mocks`. 

It won't work anymore because it's checking if `window.jasmine` or `window.mocha` is available ([see here](https://github.com/angular/angular.js/blob/master/src/ngMock/angular-mocks.js#L2567)).

### PR DESCRIPTION
**Pull request by kamilkisiela**

### CODE REVIEW

**Comment by Sanjo** [comment]
Thanks. I find it very strange, that the second init in line 16 is required. I couldn't find out why yet.

**Comment by kamilkisiela** [comment]
Totally agree. I was trying to find a reason but also had not enough time to dive more into it.

**Comment by Sanjo** [comment]
I'm getting this in for now and will check out the issue mentioned in my previous commit when I have time.

**Comment by Sanjo** [comment]
Released with 1.0.1

**Comment by kamilkisiela** [comment]
@Sanjo Thanks a lot!

**Pull request merged**
