### PR TITLE
Add support for shared specs

### LINKED ISSUE #227: Testing shared app code
Are there currently any recommended patterns for testing app code that is shared between client and server?

### PR DESCRIPTION
**Pull request by ramijarrar**
Resolves #227 

This patch requires support in Velocity for assigning multiple target frameworks to test files (I have filed another pull request for this [here](https://github.com/meteor-velocity/velocity/pull/350/files))

### CODE REVIEW

**Comment by Sanjo** [comment]
Good idea. I think I will merge the two remaining testing frameworks into one. This should have the same effect.

**Comment by ramijarrar** [comment]
:+1:

**Comment by Sanjo** [comment]
Note to me: Need to apply the commit to the integration modes only. (I have force pushed master to revert the removal of unit test modes).

**Comment by Sanjo** [comment]
Shared specs will be supported with the Meteor 1.3 release.

**Pull request closed without merging**
