### PR TITLE
Adding browser stack support.

### PR DESCRIPTION
**Pull request by vangorra**
Also fixing an issue where user provided karma configurations were
overwritten by the defaults.

### CODE REVIEW

**Comment by Sanjo** [comment]
Is there a specific option, that you need to change and was overwritten before? My intention of the code was that those options can not be overwritten by the user, because it would potentially break the test running.

**Comment by Sanjo** [comment]
Do you need to add the browserstack plugin to the plugin list via your user config?

**Comment by vangorra** [comment]
Without this change, customLaunchers was always being overwritten with:
``` javascript
        HiddenChrome: {
          base: 'Chrome',
          flags: ['--window-size=1024,768', '--window-position=-1024,0'],
        }
```

This of course will not do when attempting to run against SauceLabs or BrowserStack which depend on defining custom browsers with that parameter.

**Comment by vangorra** [comment]
I've had a bit more time to work out this issue.

meteor-jasmine is doing a few things that make using browser stack and possible sauce labs not possible.
1. The 'browsers' attribute is removed from userKarmaConfig via the blacklist.
2. The default options are overwriting the userKarmaConfig.

Since meteor-jasmine performs a lot of autoconfig, preventing the change of certain config options makes sense. However, supplying a your own karma config also suggests the dev has some idea of what they are doing and they may encounter dragons. 

The updated code allows the user's karma config to overwrite the defaults as well as removes the blacklist 'browsers' item.

**Pull request merged**
